### ISSUE TITLE
Support Pooling Condition in core spock

### ISSUE THREAD

**Issue by Fuud** [spockframework/spock#104]
Polling Condition is tricky for use - you should not forget to add `assert` at each condition. It is not clear for newcomers. But polling is widely used in integration testing where responce is evaluating by number of threads or even processes,

May be we can extend syntax for `then:` and `expect:` to support polling conditions natively.

Some possible solutions:

```
// label with spaces
"then within 5 sec, recheck period 1 sec":
  x == y

...

// polling condition description under _then_ block - not clear to understand
then:
  within(timeout: 5, period: 1);
  x == y

...

// same as spaced text but without quotes. This solution is hard (but possible) to implement
then within 5 sec period 1 sec:
x == y
```

May be there are better solutions?

**Comment by Fuud** [comment]
Also may be we do not need to support all configurations that PollingConditions have. May be we can use `period=timeout/100`. So all what we have to set in `then:` is `timeout`. 

```
"then within 5 sec":
  x == y
```

**Comment by pasa** [comment]
I am not confident in implementation difficulty, but for me this would be enough.  
```
then (timeout: 5, period: 1):
x == y
```

**Comment by leonard84** [comment]
I'm not convinced that this is an improvement. The core features of spock should be a small feature set and everything that can be done via an extension should be implemented as such. Otherwise we risk bloating spocks core to much. Of course there are features that require changes in the core, but this is not one of them.

Have a look at [PollingConditions.java](https://github.com/spockframework/spock/blob/5225ba64643f81a0c3bab0953e5ca9461a9d0f2b/spock-core/src/main/java/spock/util/concurrent/PollingConditions.java) both `within` and `eventually` are annotated with `@ConditionBlock` which causes the expressions in the closure to behave like an expression in a then block. So there is no need for an explicit `assert`. Which you can verify with the 
[PollingConditionsSpec.groovy](https://github.com/spockframework/spock/blob/5225ba64643f81a0c3bab0953e5ca9461a9d0f2b/spock-specs/src/test/groovy/spock/util/concurrent/PollingConditionsSpec.groovy)

**Comment by Fuud** [comment]
@leonard84 
>@ConditionBlock
Wow! I didn't know this cool feature. I always wrote `assert` in blocks. :( 

Related offtopic: Is there a way to mark method so all statements in it will be treated as conditions? So I can extract common validation logic from multiple test methods into one helper method.

**Comment by leonard84** [comment]
@Fuud no not yet, it is a pain point that I also would like to address. I was thinking of an annotation, e.g., `@Condition` which would be similar to `@ConditionBlock`, but would transform the methods content to behave like a then block.

Just a side note the `@ConditionBlock` has the limitation, as it is stated in its javadoc, that it only works with static closures, i.e., 
```
conditions.eventually {
  num == 42
  str == "bye"
}
```
so doing something like: 
```
def check = {
  num == 42
  str == "bye"
}
...
conditions.eventually(check)
```
will not work.

**Comment by Fuud** [comment]
Also, why `@ConditionBlock` is method-level, not parameter-level?

**Comment by leonard84** [comment]
Most likely to make `org.spockframework.compiler.SpecialMethodCall#checkIsConditionBlock` easier, it only needs to check for annotations on the method and not on its parameters.

**Comment by leonard84** [comment]
@Fuud would you agree that this Feature Request can be closed, since everything can be achieved with already available methods.
