### ISSUE TITLE
Quarkus + Kotlin + Spock = NPE on @Inject

### ISSUE THREAD

**Issue by mvniekerk** [spockframework/spock#1046]
# Issue description
Adding Spock and annotating a specification class with @QuarkusTest, doing an @Inject with some bean always result in a NPE.

# How to reproduce
1. Checkout https://github.com/mvniekerk/quarkus-test-spock-kotlin/
2. ./gradlew test

# Additional Environment information
> Version of your build tool(if used), Java, Groovy, IDE, OS etc

## Java/JDK
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Zulu 8.40.0.25-CA-macosx) (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-macosx) (build 25.222-b10, mixed mode)

## Groovy version
2.5.6

`groovy -version`

### Gradle
`gradle -version`
------------------------------------------------------------
Gradle 5.6.2
------------------------------------------------------------

Build time:   2019-09-05 16:13:54 UTC
Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_222 (Azul Systems, Inc. 25.222-b10)
OS:           Mac OS X 10.14.6 x86_64

## Operating System
macOS 

## IDE
N/A

### Gradle/Grails
    compile 'org.spockframework:spock-core:1.3-groovy-2.5'

**Comment by mvniekerk** [comment]
https://github.com/quarkusio/quarkus/issues/4797

**Comment by Vampire** [comment]
And how do you think is this related to Spock?
Quarkus does not inject the field in question, so you get an NPE if you call the method on it.
Without knowing Quarkus, I guess your problem is that Quarkus only has JUnit 5 support.
Spock is only running on JUnit 4 so far.
You can run with JUnit 5 by using the Vintage runner, but I guess the `QuarkusTest` annotation is just ignored in that case, as it is a JUnit 5 extension and the Vintage runner runs JUnit 4 tests.

You could try with a Spock 2 snapshot, as the major change in Spock 2 is, that it is JUnit 5 based, maybe it works with that.

**Comment by mvniekerk** [comment]
Ok I'll look at a Spock 2 snapshot.
The reason why I've added it here was because JUnit5 just works OOTB. But Junit5+Spock does not.

**Comment by leonard84** [comment]
> Unlike previous versions of JUnit, JUnit 5 is composed of several different modules from three different sub-projects.

> JUnit 5 = JUnit Platform + JUnit Jupiter + JUnit Vintage
https://junit.org/junit5/docs/current/user-guide/#overview-what-is-junit-5

Spock 2.0 will be using the platform and exist alongside Jupiter as another engine similar to vintage, but at the moment we don't support any Jupiter of its functionality. This could be done in a spock-jupiter adapter module but that is no trivial task and is not planned anythime soon.
