### ISSUE TITLE
Spock 2.0 release date

### ISSUE THREAD

**Issue by donbeave** [spockframework/spock#1049]
Hello!

Is there any timeline where Spock 2.0 will be released, for example, this year, or the first quarter next year?

Is I understand correctly the Spock 2.0 will be fully compatible with Groovy 3 and @CompileStatic?

Best regards,
  Alexey Zhokhov.

**Comment by kouzouigh** [comment]
Good question,
I'm wondering also if a roadmap is a available about next releases

**Comment by Vampire** [comment]
Why do you think Spock 2.0 will be any more compatible to Groovy 3 or `@CompileStatic`?
The only variant built is 2.5 with a dependency on 2.5.8.
And afaik Spock too much depends on the dynamicness of Groovy to support static compilation anytime soon more than it does already.
The main change for Spock 2.0 afaik will be, that it is based on JUnit 5 instead of JUnit 4.

**Comment by leonard84** [comment]
@donbeave 2.0-M1 has been released, groovy-3 compatibility will not necessarily be part of the first release. This depends on when groovy-3 is released and how difficult it is to get it to work with 2.5 and 3.0.

**Comment by cogman** [comment]
FYI, Groovy 2.X doesn't work with Java 14.  I'm mostly writing this due to the fact that Java 14 is due to be out soon ish and we are trying to figure out what needs to be done to make that work.  So far, it looks like our dependency chain of Pact -> spock -> groovy is broken.

If there is anything I or my company can do to help move this work along let us know.

**Comment by Vampire** [comment]
2.0-M2 was release a few hours ago and contains Groovy 3 support
