### ISSUE TITLE
Spock spec throws groovy.lang.MissingPropertyException

### ISSUE THREAD

**Issue by akuma** [spockframework/spock#1162]
# Issue description

I wrote a simple spock spec:

```groovy
package test;

class UserServiceSpec extends Specification {

    UserService userService = new UserService()
    UserManager userManager = Mock()

    def setup() {
        userService.userManager = userManager
    }

    def "test remove user"() {
        given:
        def user = new User()
        user.setId("1")
        user.setUsername("test")
        userManager.list(_) >> Collections.singletonList(user)

        when:
        def request = new UserRemoveRequest()
        request.setUsername("test")
        userService.removeUser(request)

        then:
        1 * userManager.removeUser(request)
    }
```

spock version:

```xml
    <dependency>
        <groupId>org.spockframework</groupId>
        <artifactId>spock-core</artifactId>
        <version>2.0-M2-groovy-2.5</version>
        <scope>test</scope>
        <exclusions>
            <exclusion>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
     <dependency>
         <groupId>org.codehaus.groovy</groupId>
         <artifactId>groovy</artifactId>
         <version>2.5.11</version>
         <classifier>indy</classifier>
     </dependency>
```

When I run this spec in IDEA, I got an exception:

```
groovy.lang.MissingPropertyException: No such property: request for class: test.UserServiceSpec
```

Why I can't get the reference of `UserRemoveRequest` in the `then` block? 

Thanks!

# Additional Environment information

## Java/JDK

Oracle JDK 1.8.0_241

### Apache Maven

Apache Maven 3.6.3

## Operating System

macOS Catalina

## IDE

IntelliJ 2020.1

**Comment by Vampire** [comment]
It's a bit more specific.
The variable is available in the `then` block, but not within interactions within the `then` block, because the interactions are moved to right before the `when` block.
You can read more about it here: http://spockframework.org/spock/docs/2.0-M2/all_in_one.html#_explicit_interaction_blocks

Move the `UserRemoveRequest` creation and configuration to the `given` block, then everything works fine.
That's anyway where it semantically belongs as long as you do not test the `UserRemoveRequest` creation. ;-)

**Comment by akuma** [comment]
@Vampire I got it. Thank you!

**Comment by akuma** [comment]
@Vampire I got it. Thank you!
