### ISSUE TITLE
Spock 2.0-M3-groovy-3.0 gives an out of memory error when running with Groovy 3.0.4

### ISSUE THREAD

**Issue by dilipkrish** [spockframework/spock#1186]
Here is a simple reproducible change in the [springfox library](http://springfox.io)

[Reverting this reverted commit](https://github.com/springfox/springfox/commit/9722b7e3a41208bc3e7c0409aa3e63fc27a66f52) in the master branch will reproduce this problem.

Specifically running `./gradlew :springfox-spring-web:test` [on this commit](https://github.com/springfox/springfox/commit/5f943779808bde4d40a892c9ec050bf86fffdc32) will reproduce this issue.

It works fine with groovy 2.5.12/spock 1.3 with groovy 2.5.

**Comment by szpak** [comment]
I'm not able to reproduce your problem.
```
git clone https://github.com/springfox/springfox
cd springfox
git revert 9722b7e3a41208bc3e7c0409aa3e63fc27a66f52
gw :springfox-spring-web:test
```
works fine (`gw test` fails on some `DocketSpec`, but it might be environment specific). Reset to https://github.com/springfox/springfox/commit/5f943779808bde4d40a892c9ec050bf86fffdc32 also works.

I also wasn't able to anonymously see the logs of https://circleci.com/gh/springfox/springfox/3130 .

Could you paste the error (and/or a fragment of the outout)?

Btw, it turned out that `if (result.testCount == 0) {` has a bad side effect - https://github.com/gradle/gradle/issues/7452#issuecomment-649404301 - it hides the actual internal error that might occur on the JUnit Platform (here an [example](https://github.com/szpak/spock-global-unroll/issues/7), but it can be anything else).

**Comment by dilipkrish** [comment]
Thats interesting : 🤔 

Here are some more details

Here are the JVM settings in [circle ci](https://github.com/springfox/springfox/blob/master/.circleci/config.yml#L37) and this is the [VM in circle CI](https://github.com/springfox/springfox/blob/9722b7e3a41208bc3e7c0409aa3e63fc27a66f52/.circleci/config.yml#L6-L9). This is the f[ailed build in circle ci](https://app.circleci.com/pipelines/github/springfox/springfox/158/workflows/c2fe3029-0f25-4533-8dda-2d57c37298ef/jobs/3130).

This is my environment on a Mac 
```bash 
export JAVA_OPTIONS="-Xmx2G -XX:ReservedCodeCacheSize=1G"
export GRADLE_OPTS='-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2G -XX:+HeapDumpOnOutOfMemoryError"'

 java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
   size_t MaxHeapSize                              = 8589934592                                {product} {ergonomic}
 uint64_t MaxRAM                                   = 137438953472                           {pd product} {default}
    uintx MaxRAMFraction                           = 4                                         {product} {default}
   double MaxRAMPercentage                         = 25.000000                                 {product} {default}
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```

**Comment by dilipkrish** [comment]
Im guessing that it may be related to https://github.com/gradle/gradle/issues/7452#issuecomment-649404301 Let me try without that. Incidentally I got that from the Spock migration document

**Comment by Vampire** [comment]
Exit code 137 on linux usually means the process was killed with signal 9.
128 + 9 = 137
This on linux very often happens when the OOM killer on Linux sees that the actual available RAM is exhausted, searches for the greatest RAM hog and then kills it.
This can usually be found in the syslog of the respective Linux system.

It is quite common that if you run with the same settings locally, you have no problem, as you have more RAM available or are not running on Linux.
Maybe CircleCI just does not provide enough RAM to run your tests with the new dependencies that maybe need a bit more memory. Maybe you were always at the border and just swapped over, or one of the new components really needs significantly more RAM.

So the question is, does your test process really need 3G of max heap?
Because on the free plan of CircleCI you cannot use a resource class bigger than the default `medium` which only provides 4 GiB of RAM.
So as you give the Gradle daemon itself 3 GiB max heap and then every started Java process again 3 GiB max heap using `_JAVA_OPTIONS` environment variable, you can very easily hit the 4 GiB RAM limit which will cause the OOM killer to kill your processes which just happened as it seems.

So unless you are willing to switch to a paid plan on CircleCI you should maybe consider reducing your max heap settings if they are needed at all.

**Comment by dilipkrish** [comment]
@Vampire thanks for getting back. I think its something in that test that is causing it to fail. Something that works in groovy 2.5 and Spock 1.3 but doesn't in 3.0 and spock 2. I'll dig in further and report back.

**Comment by szpak** [comment]
I agree with @Vampire - `exit value 137` is very often related to memory issues. There were no regression tests in Spock in the scope of memory used, but it might be also Groovy 3 related or you were just out of luck if it just happens occasionally.

**Comment by dilipkrish** [comment]
With some preliminary testing, I think I agree with your analysis. Thank you both for taking time to help out. I suspect that the application is behaving differently with groovy 3.0, ill dig in some more and report back!
