### ISSUE TITLE
spock mocking OAuth2Request fails when objenesis is on the classpath

### ISSUE THREAD

**Issue by ComputerDruid** [spockframework/spock#122]
For some reason, spock can't seem to mock `org.springframework.security.oauth2.provider.OAuth2Request` when objenesis is on the classpath. It works fine without objenesis.

Libraries used (build.gradle):

``` groovy
apply plugin: 'groovy'

repositories {
    jcenter()
}

dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.4.3'
    compile 'org.springframework.security.oauth:spring-security-oauth2:2.0.7.RELEASE'
    //testCompile 'org.objenesis:objenesis:2.2'
    testCompile 'cglib:cglib-nodep:3.1'
    testCompile 'org.spockframework:spock-core:1.0-groovy-2.4'
}
```

Like this, the test case passes. When the objenesis line is uncommented, the test case fails.

Test case:

``` groovy
import org.springframework.security.oauth2.provider.OAuth2Request
import spock.lang.Specification

class SpockSanityTest extends Specification {
    def "spock works"() {
        given:
        def mockOAuthRequest = Mock(OAuth2Request)
        mockOAuthRequest.getRequestParameters() >> ["test":"123"]
        expect:
        mockOAuthRequest.getRequestParameters() != null
    }
}
```

**Comment by siordache** [comment]
Here another example to reproduce this issue:
```
class A {
    private int val;

    public int getVal() {
        return val;
    }

    public void setVal(int val) {
        this.val = val;
    }
}
```

```
public class B extends A {
}
```

```
import spock.lang.Specification

class SpockSanityTest extends Specification {
    def "spock works"() {
        given:
        def b = Mock(B)
        b.getVal() >> 1

        expect:
        b.getVal() != 0
    }
}
```

The critical factor here is that A has package-private access. The test case passes if A is declared `public`.

**Comment by siordache** [comment]
Because getVal() and setVal() are declared in the non-public class A, the compiler generates bridge methods for them in B. Currently, Spock does not intercept any bridge methods, therefore the mocking fails in this case.

The problem occurs both with or without objenesis in the classpath.
For `OAuth2Request`, Spock only appears to work fine without objenesis. With the stronger condition `mockOAuthRequest.getRequestParameters() == ["test":"123"]` the test case fails even without objenesis and it reveals that `getRequestParameters()` returns an empty map.
