### ISSUE TITLE
Power assertion broken for non-static inner class after upgrade to Groovy 3.0.8

### ISSUE THREAD

**Issue by szpak** [spockframework/spock#1318]
# Issue description

Power assertion has broken for non-static inner class after upgrade to Groovy 3.0.8.

# How to reproduce

```
class PowerAssertionRegressionGroovy380Spec extends Specification {

  def test() {
    expect:
    new NonStaticInnerClass() == null
  }

  class NonStaticInnerClass {
    String toString() { "nsi" }
  }

}
```

fails wtih Groovy 3.0.7 with:
```
Condition not satisfied:

new NonStaticInnerClass() == null
|                         |
nsi                       false

Expected :null
Actual   :
```

With Groovy 3.0.8 there is:
```
Condition not satisfied:

new NonStaticInnerClass() == null
                          |
                          null

Expected :
Actual   :
```

The same assertion with plain Groovy (without Spock) works fine.

# Additional Environment information

Spock master, Groovy 3.0.8

# Additional information

The test for that case was added in autumn 2020 in #930.

Sample failure: https://github.com/spockframework/spock/pull/1316/checks?check_run_id=2475170792#step:6:130

**Comment by leonard84** [comment]
@Vampire would you take a look, as you did the original fix.

From what I can see is that the check `expr == THIS_EXPRESSION` in 
`for (Expression expr : expressions) converted.add(expr == THIS_EXPRESSION ? (T) expr : convert(expr));`
does not match anymore, since the `expr` instance of `this` is different from the constant.

![grafik](https://user-images.githubusercontent.com/1151511/116782628-a5df0f80-aa8a-11eb-8f84-5f46a0a90237.png)

@paulk-asert do you know of any changes in groovy that might cause this?

**Comment by leonard84** [comment]
I think https://github.com/apache/groovy/pull/1531 is the culprit, we will have to update the `implicit this` check.

**Comment by Vampire** [comment]
Yes, you are totally right.
See PR #1319
