### ISSUE TITLE
Preserve pending exception if cleanup-block blows up

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#142]
Originally reported on Google Code with ID 19

```
expect: false
cleanup: throw new Exception()

ConditionNotSatisfiedError should prevail
```

Reported by `pniederw` on 2009-04-03 04:58:17

**Comment by ahitrin** [comment]
Actually, such behavior could drink a lot of developer's blood in case xe doesn't know about it. In complex tests that usually appear in enterprise applications `cleanup` block usually removes objects being created during test. But when an error occures before or during creation of these objects, code in `cleanup` produces NPE or other incorrect exception. And this exception **hides other exceptions** that occure during test. In other words, consequence (failure in `cleanup`) hides actual cause of failure (failure during test).

It makes it more difficult to find the actual cause. Developer have to spend time (or **a lot of time** when xe is novice in Spock) in debugging in order to find actual cause of failure.

Just compare with JUnit:
```java
public class ExceptionTest {
    @Test
    public void wrongExpectaion() {
        assertEquals(1, 2);
    }

    @After
    public void cleanup() {
        throw new NullPointerException("cannot hide");
    }
}
```

Both errors are shown:
```
wrongExpectaion(org.example.ExceptionTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at org.example.ExceptionTest.wrongExpectaion(ExceptionTest.java:15)

wrongExpectaion(org.example.ExceptionTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.NullPointerException: cannot hide
	at org.example.ExceptionTest.cleanup(ExceptionTest.java:20)
```

But in Spock, situation is worse:
```groovy
class ExceptionSpec extends Specification {
    def catch_me() {
        expect:
        1 == 2

        cleanup:
        throw new NullPointerException("hide")
    }
}
```

Expectation error is hidden!
```
java.lang.NullPointerException: hide
	at org.example.ExceptionSpec.catch_me(ExceptionSpec.groovy:14)
```

**Comment by saicharan2311** [comment]
@leonard84 Hi , Is this problem fixed in any of the available spock versions.
Please let me know. I am Sai from India , and I am facing this issue in spock almost on a daily basis.

**Comment by leonard84** [comment]
1.2 is not released yet, you can try the 1.2-SNAPSHOT builds

**Comment by felipelo** [comment]
Plans to release 1.2 with this fix? Any roadmap for future versions? Thanks.

**Comment by leonard84** [comment]
@felipelo yes I want to release it, but there are some issues that are still open. Please test the current SNAPSHOT or jitpack builds. I need a way to collect feedback on how many tested the current (SNAPSHOT) version, just relying on no issues being opened does not really give much information.

As the PR is already merged I'm closing this issue.
