### ISSUE TITLE
@Shared and invocation testing - allow work together

### ISSUE THREAD

**Issue by LostKali** [spockframework/spock#1423]
### Is your feature request related to a problem?

If I try invocation testing over property which is marked as `@Shared` the test step orders are reversed: first Spock runs `then` block and after it, the `where` block is run.
I think this is a feature, cause in the general case we don't know the invocation order of tests in the specification and that's why such tests can pass or fail depending on the timing.
```
import spock.lang.Shared
import spock.lang.Specification

class TestSpec extends Specification {
    @Shared
    def testObj = Mock(List)

    def 'test when-then sequence'() {
        when:
        testObj.add(new Object())

        then:
        1 * testObj.add(_)
    }
}
```

### Describe the solution you'd like

1. Add a warning section to the Spock documentation about this case.
2. Add a possibility to use invocation testing over the `@Shared` properties. Probably such properties should be marked with an additional annotation.

**Comment by kriegaex** [comment]
Sorry to be so blunt, but IMO the problem sits in front of the computer in this case. Why would you share a mock? Mocks are cheap and fast. Shared fields also are meant to share state, as the annotation name implies. Are you expecting the interaction count to be shared across feature methods? Then inevitably, in all but one method it would be wrong, because a mock is only initialised once and not reset. For example, when inlining your interaction check like this

```groovy
class TestSpec extends Specification {
  @Shared
  def testObj = Mock(List) {
    1 * add(_)
  }

  def 'test when-then sequence'() {
    when:
    testObj.add(new Object())

    then:
//    1 * testObj.add(_)
    true
  }
  def 'test when-then sequence again'() {
    when:
    testObj.add(new Object())

    then:
//    1 * testObj.add(_)
    true
  }
}
```

which is a horrible thing to do and just for demonstration, the first feature method would pass and the second one fail.

Can you give me any good reason why you would declare a mock as `@Shared`? If you remove the annotation, it just works, and the mock will be newly created and initialised for each feature method or iteration, if you use a `where:` block.

BTW, `@Shared` is vastly overused, even in cases where it actually works. I think this is due to some urge to apply premature optimisations in situations where they either are not helpful or even break tests by bleeding context over to other tests.

**Comment by leonard84** [comment]
Although I would put it less bluntly, @kriegaex is correct. Mocks are not intended to be `@Shared`, although Spock doesn't enforce it. 

Re solution 1) I'm not sure it makes sense to add all the stuff that doesn't work to the documentation, it kind of feels like adding a `don't try to dry your pet in the microwave` label. The documentation never mentions the use of `@Shared` and `Mock()` together.

Re solution 2) what would the usecase be? This would definitely break when using parallel execution. Mocks are cheap, there is no reason to re-use them between iterations.

**Comment by LostKali** [comment]
Hi @kriegaex , @leonard84 ,
I totally agree with you guys - the case should be really strange for @Shared + invocation testing usage.
I intentionally simplified the example to show that the invocation order of `then` and `when` has changed. That is what I'm talking about - no warnings or messages for that case.

Probably another solution for this case is to add a warning or message to the output.

Anyway, I don't understand why the sequence of a scenario has been broken. For me the more important question: is there a possibility to get reversed `then` and `when` blocks invocation for other cases (outside of @Shared + invocation testing)?

**Comment by kriegaex** [comment]
@LostKali, can you please explain and show proof concerning what is "broken" and what specific order of things you are depending on? If you are simply talking about the fact that the interactions you want to verify in your test have to be registered on the mock at the same time as stubbing methods and the Groovy compiler takes care of the AST transformations Spock needs for that, this should not bother you. Ideally, you do not even need to know about it. If you have a simple test explaining your problem, now that we have the idea to use shared mocks out of the way, please provide an [MCVE](https://stackoverflow.com/help/mcve). My feeling is rather that you did not carefully read or fully understand the Spock manual or that you are simply overanalysing instead of just writing simple and elegant Spock tests. If you cannot explain your problem clearly, it is difficult to help you. The best way is to let code speak, because your prose rather confuses me.

**Comment by leonard84** [comment]
@LostKali what you observe is not a broken sequence of events, rather that the mock instance does not belong to the spec instance you are executing, but to the shared instance. That is why no invocations are recorded in the test instance.
