### ISSUE TITLE
Please make `Spock 1.x` compatible with `Groovy 3.x`

### ISSUE THREAD

**Issue by vanta** [spockframework/spock#1425]
### Is your feature request related to a problem?

Kind of, with the upgrade to `JDK 17` and so to `Groovy 3.0`, we'd like to avoid bumping `Spock` to `2.0` at this moment and put it for later (when tags support will be introduced). 

### Describe the solution you'd like

Making Spock `1.x` compatible with Groovy `3.x` would fix the problem.

**Comment by kriegaex** [comment]
I cannot speak for the maintainers, but want to share my thoughts with you even so: Spock does not have a history of ever backporting any new features or even bugfixes to older versions. Spock has a basically linear version history and no maintenance branches, AFAIK. Now what you are asking is not just a small feature or bugfix but a rather major-release-defining set of things. The requirement is also pretty generic, "make compatible with Groovy 3.x" can be anything in between 2 hours (probably not) to 2 months (wild guess, but think "t-shirt size XL") of effort, depending on what you mean.

If I were you, I would not hope too much for this to ever be implemented. A very small team catering to thousands of users would have to put lots of effort into this issue for a single user who wants to avoid upgrading - not because he expects upgrading to be difficult, but because he wants to wait for yet another feature which does not exist yet.

Maybe it would help you more to investigate and discuss how to achieve what you are now doing (or planning to do) with tags with on-board Spock means instead. That might yield more progress. But that is not a good topic for an issue, rather for Stack Overflow, [GitHub discussions](https://github.com/spockframework/spock/discussions) or [Gitter](https://gitter.im/spockframework/spock).

**Comment by kriegaex** [comment]
Just for reference, this issue is loosely related to previous questions about JUnit 5 tags:
* https://github.com/spockframework/spock/issues/1288
* https://github.com/spockframework/spock/issues/1069

**Comment by vanta** [comment]
> If I were you, I would not hope too much for this to ever be implemented. A very small team catering to thousands of users would have to put lots of effort into this issue for a single user who wants to avoid upgrading - not because he expects upgrading to be difficult, but because he wants to wait for yet another feature which does not exist yet.

Well, I didn't say I want to avoid migration - the problem is that tag support (tags are JUnit platform feature) is not supported in Spock 2.0 and we cannot upgrade as we heavily rely on running a dynamic set of tests (so we cannot hardcode tags in the `SpockConfig.groovy` file). 

I'm aware of these two issues you provided, as you can see I'm not the only one having a problem with it. So if you can tell me how to dynamically filter Spock 2.x specs by tags I'd be grateful. But AFAIR there's no way to do it, and this is why I raised this ticket.

**Comment by renatoathaydes** [comment]
We had the same issue more or less... were using JUnit4 `@Category` to filter tests and Spock stopped supporting that in 2.+.

We ended up implementing it our own way of filtering tests based on our own annotations because we just couldn't hold off the upgrade (several thousand Spock tests and we needed to move to Java 17)... it's not too hard to implement that, though I absolutely agree it would be best to have a replacement feature in Spock itself.

**Comment by leonard84** [comment]
> so we cannot hardcode tags in the SpockConfig.groovy file

That file is groovy code, so I'd argue that you can be way more dynamic that what you can achieve with some plain strings. Are you mixing Jupiter and Spock and are therefore stuck with the tag compatibility problem?

As for this request @kriegaex already said it, we don't have the resources to maintain multiple branches.

**Comment by renatoathaydes** [comment]
@vanta  Here's a quick suggestion to get your tests filtered not by Spock, by the test runner.. based on what we did at work.

1. create an annotation processor whose  job is just to write the name of the type annotated with an annotation.
2. before calling spock, read the file to find out which test belongs to which category (given by the annotation).
3. invoke spock with `--tests` so it will only run those tests.

It may sound hard but it's pretty straightforward to do.

I think you could even write a spock extension that only runs tests that have some annotation as well, depending on CLI or env vars. Assuming Spock extension lets you "skip" tests (which I believe is supported?)...
