### ISSUE TITLE
Add info about line number of current where: case iteration

### ISSUE THREAD

**Issue by Antoniossss** [spockframework/spock#1455]
### Is your feature request related to a problem?

I have a scenario containing around 100 cases in where: clause. I am using #iterationCount to ease navigation a little bit, but still I have to do a little bit of math to relatively quickly find the failing rule eg

@Unroll
```def '#iterationCount it should do something good for #v1 #v2 #v3..... and so on'();```

To find a line I take first like of where: clause and add iteration count to get actual line where case of interest

### Describe the solution you'd like

If it would be possible I would like to be able to include line number of iteration (case) of current where: clause 

```def '#caseLineNumber it should do something good for #v1 #v2 #v3..... and so on'();```

So I would be able to go to relevant case in no time without doing any math.

### Describe alternatives you've considered

Alternative approach that would make dev lives easier would be to include the line number of failed case "Condition not satisfied" report so it would directly indicate line of the case in use.

**Comment by kriegaex** [comment]
I think this would be difficult to implement generically, because in a `where:` block you can also have data pipes instead of data tables, and the values for those could come from anywhere, e.g. inline, read from a file, a JSON REST repsonse, an SQL call or whatever. Have you considered adding a unique number to the first column of your data table, which you could just double-click to select in the error log, copy with `Ctrl-C` and then search in the spec source code from your editor? If you have several of those data-driven methods in your spec, you might want to add prefixes to those unique IDs. But actually, if you really have tables that long, I would rather put them into extra files and actually load them via data pipes. The advantage is that each separate file would start with line 1, e.g. searching for the offset would be trivial.

**Comment by leonard84** [comment]
I agree with @kriegaex, while it may save a tiny bit of math it is quite some effort to implement, as there are many corner cases too keep in mind.

As we already have a long backlog, and the effort benefit ratio is small, I'll close this issue.
