### ISSUE TITLE
Collections matching condition not applied properly on unwrapped string collection from Optional

### ISSUE THREAD

**Issue by reirep** [spockframework/spock#1745]
### Describe the bug

Using the ==~ operator to match the elements of a list unwrapped from an optional at comparison time will interpret the list as a regex. 

In this instance the service tested returns an Optional<List<String>> (actual type: Optional<ArrayList<String>> ) and the expected result is an optional

### To Reproduce

In this example, the service returns an Optional<ArrayList<String>> containing only the string "EXPECTED-OUTPUT-STRING"

```groovy
    [...]
    def "Collection fail test"() {
        expect:
        expectedResult.get() ==~ service.call(input).get()


        where:
        input || expectedResult
        "InputString"    || Optional.of(List.of("EXPECTED-OUTPUT-STRING"))
    }
    [...]
```

### Expected behavior

The test should pass and the list not be interpreted as a regex

### Actual behavior

```
java.util.regex.PatternSyntaxException: Illegal character range near index 10
[EXPECTED-OUTPUT-STRING]
          ^

	at java.base/java.util.regex.Pattern.error(Pattern.java:2038)
	at java.base/java.util.regex.Pattern.range(Pattern.java:2830)
	at java.base/java.util.regex.Pattern.clazz(Pattern.java:2718)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2149)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2079)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1793)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1440)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1079)
	at [redacted app name]
should return the technical resource of a specific business resource([redacted test file name]Test.groovy:27)


Process finished with exit code -1
```

### Java version

JDK 18
Language level 17

### Buildtool version

Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
Maven home: C:\Users\user\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\232.8660.185\plugins\maven\lib\maven3
Java version: 18.0.1.1, vendor: Oracle Corporation, runtime: C:\Users\user\.jdks\openjdk-18.0.1.1
Default locale: fr_BE, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### What operating system are you using

Windows

### Dependencies

spock-core 2.4-M1-groovy-4.0 (scope test)
spock-spring 2.4-M1-groovy-4.0 (scope test)
Jacoco 0.8.10
junit-jupiter-api 5.9.3
Spring boot v3.1.1

### Additional context

I took as reference for the collection matching [this part of the spock docs](https://spockframework.org/spock/docs/2.3/utilities.html) and for the groovy regex string matching [this doc](https://e.printstacktrace.blog/groovy-regular-expressions-the-definitive-guide/)

**Comment by reirep** [comment]
Forgot to add, I took as reference for the collection matching [this part of the spock docs](https://spockframework.org/spock/docs/2.3/utilities.html) and for the groovy regex string matching [this doc](https://e.printstacktrace.blog/groovy-regular-expressions-the-definitive-guide/)

**Comment by reirep** [comment]
As a workaround, casting the collections as  Set and not using "==~" will work

**Comment by Vampire** [comment]
Can you share a more complete example?
This works fine: https://gwc-experiment.appspot.com/?g=groovy_4_0&codez=eJyVUVFLwzAQfs-vCHlqhPUHzHUgc8hA7Fg7EEQkay8zEtqSXHXi6m83aW2cAx-8l1zuvu_L3ZdCC2tpDhYpHBCq0tKsgUJJVQhUdUU_CHVRgqRsUWsNRV-VQmmKjsUi_g3xYQHbZhquGZhXVYArD2dCM2x3J3gfhdA6unjidD6naePVhY5rGT2w5f16uciX15N0m6-3-STLN6u7G_bIA78LWUjg4MbH6dkdyg3YVmO8B3QTJ8nnOFTcv6-qpkU-dEngvj2DgR-pHkSPxzPN0GcrD8jQqGrPfMFBTze6VRb9-ddinP9fStb1yOtIR4iqEIwUzuzR_MHtkTy7Mka8e_psUHeu9w6kuxe307AjvyTdrz_6ArjZnzY

**Comment by reirep** [comment]
Sorry for the non-working example / reproduction set.
It seems that, in order for the bug to be reproducible, the comparison needs to be done inside an if.
Working reproduction code: [https://gwc-experiment.appspot.com/?g=groovy_4_0&codez=eJydUcFuwjAMPdOvsHpqJtEPYBRpYtWENK2IFmm3KRSXZcraKnE30Oi-fUk7AkU7zRcnzsvze3YuudaQoSbAPWG51ZDWmItC5JxEVcKXBya2WIA_r6TEvKsWXEgg88sP2C_EhkZq6om7pqg-RI6m3OcIUmo2F3gbOZcyuHlhMJtBUlt2LsOqCB6FJpv9-HkZz7P4fpyss-U6G6fZavH04DPmaFp3cgfcGxc0GXQSRdCXcbtC3UgKhY7fazoEjA019V460WGnT5R1Q-yMH6BbQKnxwtZodNVnh2TmFEXff7J2r0NGz10_X1Hh2Uf3BY5HGHZw7_7CAlJSotz5tmCg_5hq6xkJoiRUBTeLOy2yt3jim94pxQ-Wcdo3NBvsfCWbN6Ot18puvXbg7Qd2vLCD](https://gwc-experiment.appspot.com/?g=groovy_4_0&codez=eJydUcFuwjAMPdOvsHpqJtEPYBRpYtWENK2IFmm3KRSXZcraKnE30Oi-fUk7AkU7zRcnzsvze3YuudaQoSbAPWG51ZDWmItC5JxEVcKXBya2WIA_r6TEvKsWXEgg88sP2C_EhkZq6om7pqg-RI6m3OcIUmo2F3gbOZcyuHlhMJtBUlt2LsOqCB6FJpv9-HkZz7P4fpyss-U6G6fZavH04DPmaFp3cgfcGxc0GXQSRdCXcbtC3UgKhY7fazoEjA019V460WGnT5R1Q-yMH6BbQKnxwtZodNVnh2TmFEXff7J2r0NGz10_X1Hh2Uf3BY5HGHZw7_7CAlJSotz5tmCg_5hq6xkJoiRUBTeLOy2yt3jim94pxQ-Wcdo3NBvsfCWbN6Ot18puvXbg7Qd2vLCD)

**Comment by AndreasTu** [comment]
I would say this is not a Spock bug.
As the documentation in "Implicit and explicit conditions" states: "all top-level expressions in these blocks are implicitly treated as conditions".
Your implicit condition `xpectedResult.get() ==~ service.call(input).get()`  is not at the top-level (your have an if in between), so it is not converted into a condition by Spock.
Then the normall Groovy operator-logic for `==~` applies and the error message is issued by Groovy itself.

You would need to add the `assert` keyword there:
```groovy
expect:
if(expectedResult.isEmpty()){
    assert service.call(input).isEmpty()
 } else {
    assert expectedResult.get() ==~ service.call(input).get()
}
```

If you do not add the `assert` none of these `expect:` conditions is asserted.
So also your workaround, would not yield the correct results, because it is not asserted without the `assert` before, if your have an `if()` there. You can see that [here](https://gwc-experiment.appspot.com/?g=groovy_4_0&codez=eJydUcFOwzAMPdOvsHJqkLYPGGMSGhWahOi0dhI3lGUOBIW2SlzYxPrvJCvLVokTvth-ebGfbWmEc1CiI8AdYbV1UDQotdJSkK4r-E7A2xYVsHltDMojqoQ2QP4XS_kvJZhDaptJTAu0n1qih3t_CwW1mwt-MCmMSa9fOMxmkDehujDjWqWP2lHwLHteZvMyux_l63K5LkdFuVo8PTDOY5kuRjHAnZ-CJoNOWqU9jNsVutbQWLvso6F9yvlQkzcljMMB2AF66EL91d-0JKZfb2jxrEFXTUtwOMBQRXxni0AoyOrqlQXAU_-xkS7xEnRFaJXwSz8dodd9qje9s1bsQ8Vp39Bv_3iJfPPutfVa-U3SDWb7Abb1mGc) the test is not failing, although it tries to assert `false`.


See the working [sample](https://gwc-experiment.appspot.com/?g=groovy_4_0&codez=eJydUU1vwjAMPdNfEfXUTKI_gAHSxKoJaVoRLdJuU0gdlilrq8TdQKP77UtaWijiNF_i-OP5PZsrZgxJwSCBPUKeGZKUwKWQnKEscvLjEWsZCOIvCqWAN1HBpCJou_yAnkqcGcCqnPTfBPSX5GDD7TsjCVbbi3pnnCkV3L1RMp-TuHToTIWFCJ6lQff60esqWqTR4zjepKtNOk7S9fLlyae0h6l7r3dgb1XgZDBJiqANQ7YGUykMpYk-SzwElA45ObN7AY0d97ChKfOyQnpuGzTVBJSBC3Wj0QnjauoO0G5tNvu9Cd5kh8Be__1-Bw1nVU0LOR6vJvR5f-kKEtQy3_kuYEv_sePasxRkjqAFs2fsztoq7fCmD1qzg0OctgPtPRtd8fbDcmu50nuvHmj7A9tMtec) with the `assert` keyword.

**Comment by Vampire** [comment]
Only top-level expressions are considered implicit assertions.
The code inside `if` is not top-level and thus not treated as implicit assertion.
This means that while you get rid of the compile error by using set and equals, it is still not what you want, as it would never fail, as they are simple statements, not assertions.

I like to say "never trust a test you didn't see fail for the right reason". And this test you would never see fail for the right reason.

Add the explicit `assert` keyword to the two statements inside the `if` to make them explicit assertions, then it works as expected.

**Comment by reirep** [comment]
Thanks a lot for the answer and the clarification on the matter.
To be able to see the important information that I missed, where is it documented ? I may need to read that part again ^^

**Comment by AndreasTu** [comment]
@reirep 
https://spockframework.org/spock/docs/2.3/spock_primer.html#_implicit_and_explicit_conditions
