### ISSUE TITLE
Upgrade Groovy 3.x in 2.4-groovy-3.0

### ISSUE THREAD

**Issue by rpalcolea** [spockframework/spock#1797]
### Is your feature request related to a problem?

JDK 21 support out of the box

### Describe the solution you'd like

Hi folks, 

I was looking at [2.4-M1-groovy-3.0](https://mvnrepository.com/artifact/org.spockframework/spock-core/2.4-M1-groovy-3.0) and it brings Groovy `3.0.13` which doesn't support JDK 16+

Looking at https://groovy-lang.org/changelogs/changelog-3.0.17.html#changelog, it seems that 3.0.17+ would be nice to have as ASM 9.5 supports JDK 21

What are your thoughts on bumping groovy for 2.4-groovy-3.0? and also wondering if there is a potential release coming up?

### Describe alternatives you've considered

Yes, introducing groovy myself but I think since spock needs groovy transitively, it might make sense to just upgrade it here

**Comment by szpak** [comment]
Thanks for you request. However, in Git the Groovy 3 version is already bumped to 3.0.19:
https://github.com/spockframework/spock/blob/efc62137180f43feda34771f5a08386840f61760/gradle/libs.versions.toml#L3

so it should work out of the box in the next release. For 2.4-M1-groovy-3.0, it would be best - as you also suggested - to override version in your project.

Regarding the next version, yes, it would good to the at least M2 "soon" as there have been many changes since December 2022 :-/.

Closing it, as the version is effective already bumped.
