### ISSUE TITLE
Upgrade Groovy version. Groovy 3 -> Groovy 5.0.0-alpha-2

### ISSUE THREAD

**Issue by oURMIo** [spockframework/spock#1840]
### Is your feature request related to a problem?

I faced a problem with an outdated JDK. The maximum supported JDK version for Spock is 11, while JDK 21 has been released recently. It's worth considering upgrading Groovy from version 3 to Groovy 5

### Describe the solution you'd like

The libraries currently use Groovy 3. It is worth updating, and you may consider updating the code where possible

groovy - https://central.sonatype.com/artifact/org.apache.groovy/groovy-all/5.0.0-alpha-2

### Describe alternatives you've considered

Upgrading to version 21 may not be straightforward, so for starters, it's advisable to transition to the next Long-Term Support (LTS) JDK, which is JDK 17

### Additional context

I encountered a challenge when tasked with writing tests for the project. I had to choose between Kotest and Spock. Due to Spock not supporting the minimum required JDK, I had to use Kotest, and it left me somewhat disappointed.

I'm considering moving forward with the progress, thereby improving the project

**Comment by kriegaex** [comment]
Why do you use a Groovy 3 version of Spock instead of a Groovy 4 version?
https://central.sonatype.com/artifact/org.spockframework/spock-core/versions

![image](https://github.com/spockframework/spock/assets/1537384/43d46184-e31e-4eb9-b0a9-68841a93585a)

Since August 2022, i.e. ~15 months, there is an official Groovy 4 version, which of course runs just fine on JDK 17 and probably also on more recent versions, if you compile to target 17 or below. Which JDK 21 language features unavailable on 17 are you using? Forgive the questioin, but most people demanding tool upgrades actually do not use any modern language features, they just falsely believe that they cannot use new JDKs, because they compile to more recent targets without thinking and without actually needing it. Your case might be different, but chances are that you just want to run Java 11 or 17 code on JDK 21, which should be fine.

**Comment by oURMIo** [comment]
It's still too early to transition to JDK 21
