### ISSUE TITLE
Support both constructorArgs and default interactions

### ISSUE THREAD

**Issue by chrylis** [spockframework/spock#1896]
### Is your feature request related to a problem?

I am trying to mock an abstract service class that has required constructor parameters and also define default interactions. However, when I try to use `Mock(constructorArgs: [...]) { interact() }`, I get `unexpected input` on the `{`. 

### Describe the solution you'd like

I would like to be able to supply a block of default interactions after a `Mock` invocation that uses parentheses to pass configuration to the mock.

### Additional context

I believe that Spock takes over the parsing for this syntax, so I haven't been able to track down the code where it is implemented to see if there is an alternative syntax that supports this already. If there is, then documentation would be helpful.

**Comment by AndreasTu** [comment]
Hi @chrylis,
I am not sure what you mean. Can you give a more elaborate code example of what you want to accomplish?

Because constructorArgs and interactions during `Mock` construction exist and is working:
```groovy
class MyTest extends spock.lang.Specification {

  def "Test"() {
    given:
    MyService service = Mock(constructorArgs: ["A"]) {
      getArg1() >> { callRealMethod() }
      doMethod() >> "MockValue"
    }

    expect:
    service.getArg1() == "A"
    service.doMethod() == "MockValue"
  }

  static class MyService {
    private String arg1

    MyService(String arg1) {
      this.arg1 = arg1
    }

    String getArg1() {
      return arg1
    }

    String doMethod() {
      return "doMethod" + getArg1()
    }
  }
}
```
See also the [groovy web console](https://gwc-experiment.appspot.com/?g=groovy_4_0&codez=eNp1kMFqwzAMhu95CuFTyiCwayGFPkAuS9ll7GAcNTUzdrCV0FL67pVdZ0kGMxgb_dKnX1JGhgDN7YSBAK-EtgsQBqd-KiNtX7UDKn3WSpJ2Fu5FAdDhGUTMF-WOI8Cn1xPaffo2txb9pBVCyG8NDeNK5WwgPypy_uj7sIcvcRTfM4EZSBx_Z-bhAHdQ0pgPlKZBuriOo4-c17nfECeKyP6UZkSR9EeRHryyb3o5yj6qpUFdA_feiCtqVDfUxAzEK1Cg8r7mIV_uB68nSQgteW17kNym2G6jXEnLzHTRoYohXlIqWo2QCxbXc5FHGr39L381yJ8CMUsC3hZsRsSbQfN5Avr0m1g) for the example.

**Comment by chrylis** [comment]
I originally tried this with a field declaration, but I also reproduce in a `given:` block.

```
    def 'bug'() {
        given:
        S3Service jets3t = Mock(constructorArgs: [new AWSCredentials('key', 'secret')]) {
            putObject(*_) >> throw new UnsupportedOperationException()
        }

        expect: true
    }
```
produces
```
InvocationTargetException: startup failed:
/path/to/project/media/images/resize/ImageResizerImplTest.groovy: 95: Unexpected input: '{' @ line 95, column 89.
    redentials('key', 'secret')]) {
                                  ^
```

I am seeing this behavior on groovyc 4.0.18 and the GRECLIPSE nightly with Spock version 2.3-groovy-4.0.

**Comment by AndreasTu** [comment]
You need need to wrap your code answer of an interaction in `{}`
 like `putObject(_) >> {throw new UnsupportedOperationException()}`
 
 The answer here is a code block because of the throw, so it needs to be a `Closure` therefore you need `{}`.
 
```groovy
class MyTest extends spock.lang.Specification {

     def 'bug'() {
        given:
        MyService jets3t = Mock(constructorArgs: [new AWSCredentials('key', 'secret')]) {
            doMethod(_) >> {throw new UnsupportedOperationException()}
        }

        expect: 
        jets3t != null
    }
    
    static class AWSCredentials{
        AWSCredentials(String key, String secret){}
    }
    
  static abstract class MyService {
    private String arg1

    MyService(AWSCredentials arg1) {
      this.arg1 = arg1
    }

    String getArg1() {
      return arg1
    }

    String doMethod() {
      return "doMethod" + getArg1()
    }
  }
}
```

 See [groovy web console](https://gwc-experiment.appspot.com/?g=groovy_4_0&codez=eNp1UU1rwzAMvedXaL0k2Uqh7FZooYwdQw_Z2GGM4Tqq4zbYxlb6Qcl_n_PRJN2YDkaW5af3nnjBnIPk8oaOAM-EKnPgjOaHWcGUmKUGudxJzkhqBdcggDoy3EG4LUUYxb4GXQh5RLXor8klRXuUHGGP5J4JlpB43Ihr5ciWnLRdW-EW8KnwBOuP9MVihookK1wUHvASTiF0yC1SGH-NB9VhStps98gpevyOYbWCK-VWn6DGeleuNEZbwmxj0DbcX88cTZ1EcdUDVUGf4tkrpQX0hY70wxJUWRRB216fzeHIo3LgjX333AeevzSlZKUS4JVNoctbefG1usfv0NnWG8U4dWMGQ9sRxsojI7xhMSvmrZ6-Mbpn0LQMRlIu3awu-c00n0eWdJgCye9oPlqzp1ta9V9_phOkXGd_P0xuTxN4GmB72VUw2kUdP-ezwvE)

**Comment by AndreasTu** [comment]
See also documentation: [Performing Side Effects](https://spockframework.org/spock/docs/2.4-M2/interaction_based_testing.html#_performing_side_effects)
