### ISSUE TITLE
Global GroovyMock aren't cleaned

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#445]
Originally reported on Google Code with ID 323

```
Given these two Spec :

class FooServiceSpec extends Specification {

     def 'doSomething() should do something'() {
          setup:
          GroovyMock(Bar, global: true)

          when:
          service.do()

          then:
          1 * Bar.life() >> 42
     }
}

class BarSpec extends Specification {

     def 'computeLife() should return 42'() {
          setup:
          def bar = new Bar()

          expect:
          bar.computeLife() == 42
     }
}

If I run my tests and FooServiceSpec is executed before BarSpec, 'computeLife() should
return 42' fails with a NPE on 'bar.computeLife()'. If FooServiceSpec is executed after
BarSpec, everything works.

So my guess is that the mocking of the static method 'Bar.life()' is not cleaned, so
when I do 'new Bar()' it returns null.

FYI, I'm using Spock 0.7-groovy-2.0 with Grails 2.2.3 and spock-grails-support 0.7

To run the tests in a specific order in do :
    grails test-app -unit FooServiceSpec BarSpec              >>> Fail
    grails test-app -unit BarSpec FooServiceSpec              >>> OK

This is really annoying cause I can't control which test is executed first, so my Jenkins
randomly fails to build the project.
```

Reported by `gcoutant@excilys.com` on 2013-07-29 12:55:22

**Comment by sting2804** [comment]
i have the same problem

**Comment by jeff-blaisdell** [comment]
:+1: still searching for a way to cleanup.

**Comment by topera** [comment]
Same problem, fixed with this workaround: @ConfineMetaClassChanges([Bar]) in test method.

**Comment by reitzig** [comment]
@topera's workaround works only for global mocks defined in the test method; if defined in `setup()`, the mocks still leak.

**Comment by orgi** [comment]
Looks like this issue didn't get much attention in the past years.
Is the `@ConfineMetaClassChanges([Bar])` (@topera thanks, btw.) the solution to this or maybe should something be changed in Spock itself to address this?

**Comment by pozhidaevak** [comment]
@topera's solution works for me for mocks defined in `setup()` I just added `@ConfineMetaClassChanges([%%MOCKED_CLASS%%])` as a class-level annotation.

However, I think this should be fixed and the behaviour with annotation should be by default

**Comment by kriegaex** [comment]
There was some related discussion on [Stack Overflow](https://stackoverflow.com/q/71616518/1082681), please also read the comments. The result for now is that there do not seem to be any issues when trying to reproduce that in Spock. @leonard84 and I posted examples on Groovy Web Console. Mine contained a bug, which is why at first I thought I can reproduce the problem, but actually I could not. So if anyone here can come up with a minimal reproducer which does **not** involve Grails, I am sure that Leonard would look into it. Otherwise, this might be a Grails issue and we could close it here. So to whoever is still interested in getting to the bottom of this: Please respond. Thank you.
