### ISSUE TITLE
Mock invocation order is based on method return order, not invocation

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#475]
Originally reported on Google Code with ID 353

```
This fails:

   def "spock bug"() {
    given:
    def r1 = Mock(Runnable)
    def r2 = Mock(Runnable)
    def r3 = { r1.run() }

    when:
    r3()

    then:
    1 * r1.run() >> { r2.run() }

    then:
    1 * r2.run()
  }

While this passes:

  def "spock bug"() {
    given:
    def r1 = Mock(Runnable)
    def r2 = Mock(Runnable)
    def r3 = { r1.run() }

    when:
    r3()

    then:
    1 * r2.run()

    then:
    1 * r1.run() >> { r2.run() }
  }

Spock thinks r2.run() was called first because it returned before r1.run().
```

Reported by `luke@gradleware.com` on 2014-03-12 21:53:34

**Comment by simontunnat** [comment]
This is currently hitting me hard because I'm trying to mock the behaviour of a Jenkins Pipeline to test a Jenkins Pipeline library I'm writing.

There is code like this:
`
pipeline.stage("Build") {
  doSomeStuff()
  doSomeOtherStuff()
}
`

The following test succeeds:
`
then:
1 * pipeline.stage("Build", _) >> { _, closure -> closure.call() }
1 * pipeline.doSomeStuf())
1 * pipeline.doSomeOtherStuff()
`

When I try to the order of the execution as well the test fails:
`
then:
1 * pipeline.stage("Build", _) >> { _, closure -> closure.call() }

then:
1 * pipeline.doSomeStuf())

then:
1 * pipeline.doSomeOtherStuff()
`
With this error message:
`
Wrong invocation order for:
1 * pipeline.stage(name, _)   (1 invocation)

Last invocation: pipeline.stage("Build", [...])
`
