### ISSUE TITLE
argument check should fail but it is passing

### ISSUE THREAD

**Issue by jaroslawk** [spockframework/spock#59]
Hello,

I got the following setup:

public class BuggyCheck extends Specification{

```
class UnderTest{
    SomeService someService
    public update(int i){
        someService.update(i)
    }
}

class SomeService{
    public void update(int i){
    }
}

def "should fail here"(){
    UnderTest underTest = new UnderTest()
    SomeService someService = Mock(SomeService.class)
    underTest.someService = someService
    when:
    underTest.update(33)
    then:
    1 * someService.update {def simpleClass ->
        1==3
        1==1
    }
}
```

}

from what I have seen in the code you check if the output of the Closure is Truthy 
Can this be adjusted to verify all the lines for the Truth ?

Regards, 
Yahro

**Comment by SQiShER** [comment]
I think this can be remedied by changing your code to this:

```groovy
    1 * someService.update {def simpleClass ->
        assert 1==3
        assert 1==1
    }
```

This will make the test fail with the following message:

```
Condition not satisfied:

1==3
 |
 false
```

At least that's what I usually do. However, it would be much nicer if the error message would mention that this assertion failed because of a mismatched argument.

Hope this helps!

**Comment by jaroslawk** [comment]
Correct. As long as you know that under consideration of verification is taken return value of Closure under argument. This is misleading since under section where you can simply type:

where:

1==3
1==1

I home this explains my concern.

**Comment by jaredsburrows** [comment]
So are you saying this is a bug or you want to have to explicitly `assert` that variables under `then:`?

**Comment by jaroslawk** [comment]
It is misleading. Preferably it should work like under then: section.
For person which do not understand what is happening it would be easier to get started with this.

It is a feature request then :)

**Comment by vanta** [comment]
This is dangerous as last assertion result is returned and all above can be falsy and test will still be green. We had such issues before. Or you have only one assertion so `{a == b}` is enough, but when you add another one you need to remember either to add it with `&&` (`{a == b && c ==d }`) or prefix all of them with `assert`.

**Comment by leonard84** [comment]
This is not a bug the reason is, that it is perfectly fine to have multiple calls to the same method with different argument matchers, using `assert` would break the first time it is called. This might be ok for your specific use-case, when you only have one call, but it would definitely break other code.

So your options are to use boolean logic, explicit assertions, or `with`/`verifyAll`.

**Comment by jaroslawk** [comment]
Ok. Thank you for an explanation.
