### ISSUE TITLE
Making Failure related objects Serializable

### ISSUE THREAD

**Issue by MarkBramnik** [spockframework/spock#647]
# Issue description
### Spock version: groovy-2.4-rc-2

In JUnit all the "transport" objects like `org.junit.runner.Description, org.junit.runner.notification.Failure` and so forth intentionally implement `java.io.Serializable` interface.
I'm writing a custom runner and I would like to serialize the results of the test execution.
However, when a spock test fails, the `org.junit.runner.notification.Failure` object contains the following instances:

`org.spockframework.runtime.SpockComparisonFailure`
 -->`org.spockframework.runtime.Condition`
--> `org.spockframework.runtime.model.ExpressionInfo`
and so on 
All of them are not Serializable which kind of contradicts with the JUnit contract (at least IMO)

It could be great if one could fix that :)

Thanks a lot in advance
# How to reproduce

Register the implementation of `org.junit.runner.notification.RunListener` in the custom Runner
Create any trivial test that fails and check the Failure object in the listener callback method.
## Java/JDK

Applies to any supported Java version
## Groovy version

Applies to any supported Groovy  version

**Comment by hblohm** [comment]
Hi, I am facing the same issue: I have a unit test runner that serializes and de-serializes junit Description objects. Currently the integration with Spock is brokendue to this problem.

**Comment by leonard84** [comment]
@MarkBramnik, @hblohm the main problem is that most of these classes have objects or list of objects (e.g, the actual value instances that failed the comparison check, or the mock object) that may or may not be serializeable. Furthermore, just making those fields transient will lead in rather unexpressive results.

**Comment by MarkBramnik** [comment]
@leonard84 I see your point. However I see this as a kind of contract that JUnit establishes. And it could be great, if spock as a JUnit extension could also obey this contract. 
AFAIK, a description and all the objects inside it after all are used by IDEs and reporting framework so they contain just a bare minimum to _show_ descriptive results.

Frankly speaking I was trying to create a [framework](https://github.com/MarkBramnik/rtest) for remote execution of integration tests inside the server (Remote JVM) - something that IMHO could be an interesting contribution to the Spock ecosystem. Not to advertise or something, just to illustrate why this Serialization could be beneficial.  

So in this framework I originate a test run on some remote JVM and this produces a call to the server that actually runs the tests, and when the results are available it is supposed to send them back to client to be shown in IDE, reports or something.
The lack of ability to serialize results back to to the running remote client makes it virtually impossible to implement.  What do you think?

**Comment by hblohm** [comment]
@MarkBramnik That is exactly my use case as well (https://ztheworld.wordpress.com/2013/10/22/in-system-testing-re-invented/). In an old version (Description was not even serializable), the test Description object, that is retrieved using the annotation configured Runner, was serialized to the remote execution using JSON (as a best effort). That was suffering from the fact that Description is not really a POJO and some plumbing was necessary. Now it is serialized using Java serialization. That approach was not working too well with some testing frameworks (namely Spock) because the annotations that are conveyed using the Description object are not de-serializable. However, in order to run the test server-side, you do not really need the whole Description but only for sorting and filtering really. I fixed the serialization problems (client->server) by purifying the Description (removing annotations) an on the way back by a substituting non-serializable failures with a text replacement. The code is part of a larger framework (z2) but it should be quite understandable. Start here https://redmine.z2-environment.net/projects/z2-base/repository/base/revisions/master/show/com.zfabrik.dev.z2unit if you care.
