### ISSUE TITLE
GroovyMock object casting returns null

### ISSUE THREAD

**Issue by kalgm** [spockframework/spock#661]
# Issue description

> When using GroovyMock, casting to the original object returns null.
# How to reproduce

```
def TodoItem todoMock = GroovyMock TodoItem
todoMock as TodoItem != null
```
# Result

```
Condition not satisfied:

todoMock as TodoItem != null
|                     |
|                     false
com.sample.TodoItem@6722db6e
```
# Additional Environment information

> spockVersion = '1.0-groovy-2.4'
> javaVersion = '1.8.0_102'
> groovyVersion = '2.4.7'
### Gradle

---
## Gradle 3.0

Build time:   2016-08-15 13:15:01 UTC
Revision:     ad76ba00f59ecb287bd3c037bd25fc3df13ca558

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Mac OS X 10.11.6 x86_64
## IDE

> IntelliJ

**Comment by angry-cellophane** [comment]
Let's compare three expressions:
```
        given:
        def list = GroovyMock ArrayList

        expect:
        ((ArrayList)list) != null // #1 true
        list.asType(ArrayList) != null // #2 false
        list as ArrayList != null // #3 false
```

#1 compiles to something like this:
`ScriptBytecodeAdapter.castToType(list, ArrayList.class)`
#2 compiles to:
`list.asType(ArrayList.class)`
#3 compiles to:
`ScriptBytecodeAdapter.asType(list, ArrayList.class)`

Now let's take a look at these methods.
- ScriptBytecodeAdapter::castToType does quite sophisticated comparision between the given class and the object's class. The main point is this work is done by outside class (DefaultTypeTransformation.class). 

- list.asType - since list is a mock all its methods should have mock implementation or return default values. We don't define an implementation of the asType method, therefore null is returned.

- ScriptBytecodeAdapter::asType has same behaviour as the asType method according to the groovy [doc](http://docs.groovy-lang.org/latest/html/documentation/#_coercion_operator).

Therefore, the original behaviour is expected
```
def TodoItem todoMock = GroovyMock TodoItem
todoMock as TodoItem != null
```
There is no issue here.

**Comment by leonard84** [comment]
I agree with @angry-cellophane
