### ISSUE TITLE
Hamcrest matchers as argument constraints

### ISSUE THREAD

**Issue by facboy** [spockframework/spock#692]
In this old discussion it was suggested that Spock might some day support Hamcrest matchers as argument constraints, did this every go anywhere?

https://groups.google.com/forum/#!topic/spockframework/4W74ZGDzTQk

**Comment by facboy** [comment]
Actually I've found that this does work if you just use a Hamcrest matcher as an argument in the stub declaration.  Unfortunately, if there is a match failure it is not very informative about what failed as it doesn't  use the matcher's `describeMismatch()` method.

**Comment by leonard84** [comment]
Yes, the reporting regarding unmatched interactions is not very good in general. You could open a new issue regarding its improvement, however I think it is not trivial to fix, since it must also be able to deal with a large amount of interactions.
The requested feature is present as it is, so I'm closing this issue. If you'd like you could add the Hamcrest support to the documentation in a PR.
