### ISSUE TITLE
Feature request: spying on concrete objects

### ISSUE THREAD

**Issue by jdpopkin** [spockframework/spock#77]
I would like to be able to create a Spy using a concrete object rather than a constructor and list of constructor arguments. (I need this in order to set up private fields via introspection.)

I know this is a weird use case, but I'm [not the only one](http://stackoverflow.com/questions/28369398/can-spock-spy-for-real-object) interested in this. Would it be possible for a feature like this to be added in the future?

**Comment by cdeszaq** [comment]
:+1:

**Comment by twicksell** [comment]
+1

**Comment by Vampire** [comment]
This is available since 1.1-rc-4 and can be closed

**Comment by VidalOrtizWL** [comment]
Hi guys @Vampire, @leonard84, @twicksell 

I know this is an ooooold ticket, but I just noticed that the implementation for Spies on concrete instances does not include the +Closure version of SpyImpl in SpecInternals.java.

This means I cannot provide interactions to the Spy, which is usually the purpose of creating them.

**Comment by Vampire** [comment]
1. Please do not ping random people
2. That there is no closure variant of the factory method does not mean this feature is not implemented and is actually reported by me at https://github.com/spockframework/spock/issues/1028
3. Of course you can provide interactions, just not in such a closure block. You can do it in your feature method, you can do it in a setup method, you can do it with other Groovy means like `Spy(foo).tap { 1* _ }` or `Spy(foo).with(true) { 1 * _ }` there are many ways, just not the closure one which is a bit unnice and inconsistent to the others which is why I opened an issue for it, but they are still fully functional.

**Comment by leonard84** [comment]
As there is a separate issue #1028 I'm closing this one.
