### ISSUE TITLE
Improve documentation concerning callRealMethod()

### ISSUE THREAD

**Issue by kriegaex** [spockframework/spock#830]
I got curious when reading [this question](https://stackoverflow.com/q/49212904/1082681) on StackOverflow. I also found and posted the [answer](https://stackoverflow.com/a/49216680/1082681).

So basically the Spock manual mentions `callRealMethod()` only for spies, not for mocks or stubs. But oh - surprise, surprise - it works for all of them, which was rather unexpected for me.

Furthermore, the Javadoc for [`IMockInvocation`](https://github.com/spockframework/spock/blob/spock-1.1/spock-core/src/main/java/org/spockframework/mock/IMockInvocation.java) says:

> Delegates this method invocation to the real object underlying this mock object, replacing the original method arguments with the specified arguments. If this mock object has no underlying real object, a `CannotInvokeRealMethodException` is thrown.

Two problems here:
1.  The Javadoc is not found online in the API doc, so maybe the Javadoc was not created or uploaded correctly.
2. The Javadoc does not explain what "underlying real object" is supposed to mean. Neither does the Spock manual.

I did find out what it means: An "underlying real object" is available whenever a non-interface type is mocked, stubbed or spied.

So my suggestion is:
- Explain "underlying real object" in the Javadoc and make sure the Javadoc is generated and uploaded at all.
- Mention in the Spock manual that `callRealMethod()` works for mocks, stubs and spies alike.
- Mention in the Spock manual that `callRealMethod()` only works if the mocked object is not an interface type.

**Comment by kriegaex** [comment]
After almost a year it would be nice to see some action here. :-)

**Comment by leonard84** [comment]
@kriegaex  one reason that this is not advertised, is that you should use a spy if you want to call the real implementation. And as for underlying real object, if you can't instantiate it, e.g. creating a mock of an interface will work quite well, but using `callRealMethod` will fail, I'm not sure about default methods without checking into the code.

We usually accept pull requests that improve the documentation.

**Comment by kriegaex** [comment]
@leonard84, it is rather difficult to create a PR for something I don't completely understand. Is is a bug? Is it intended? What are the limits of calling this method (you just mentioned one)? IMO the behaviour should be changed to only perform the call for spies, not for mocks or stubs. But documenting the current behaviour is also acceptable for me.

And BTW, I have no influence whatsoever in how you create Javadocs.

So maybe it really would be better if a maintainer who knows the project would take care of this issue.

**Comment by leonard84** [comment]
@kriegaex see http://spockframework.org/spock/docs/1.3/all_in_one.html#ALaCarteMocks and have a look at `org.spockframework.mock.MockNature`. Under the hood there are no `Mock`/`Stub`/`Spy` types only a collection of behavior. So we won't change Spocks behavior, in this regard. Basically `callRealMethod()` works as long as there is a proper implementation for that method, either as `default` method on an interface or just a normal method on a class.

Your answer on the SO post was quite accurate and the code you posted also shows that default methods are supported. We are open to suggestions for a better wording or additional notices. It is helpful if the one who had the question writes it down so that he could have understood it in the first place. For others it might have been obvious and so it has not been mentioned.

**Comment by kriegaex** [comment]
Would you please merge this PR?  Actually now the PR got refreshed because I committed another documentation fix for the same file concerning à la carte mocks. Sorry that the PR is not clean anymore, I forgot to put both commits into different branches, they are both on my fork's master.

**Comment by chrylis** [comment]
Marginally related: #729.
