### ISSUE TITLE
Clarify if Mock / Stub / Spy are welcome in the where: block

### ISSUE THREAD

**Issue by sdoeringNew** [spockframework/spock#848]
Regarding the Spock documentation Mocks are allowed after the then: block or before the when: block.

Does that include the where: block, too?
They work there, too, but is it a good practice?

Please clarify in your documentation.

Furthermore:
The strict mocking invocation: `0 * _` does not apply to Mocks specified in the where: block. Is it a feature or a bug?

In order to make them strict, you have to write:
```groovy
where:
user = Mock(User, {0 * _})
```

**Comment by leonard84** [comment]
Mocking is partially supported in where blocks, but it is not a good practice since you can only define restrict calls, not require them, e.g., you can say nothing should be called on the user, however you can't say that one method should have been called at least once. This has to do with the way mocks are verified, each [given]-when-then is surrounded by an interaction scope in which the mock interactions are verified, since the where block is outside this scope the required interactions cannot be verified and will never fail. 

Related http://spockframework.org/spock/docs/1.1/all_in_one.html#_where_to_declare_interactions, improvements to the docs are welcome.

**Comment by sdoeringNew** [comment]
So that is not okay?

```Groovy
public List methodToTest(final List list) {
    return list
}

def "methodToTest: returns the argument"() {
    when:
    final def result = methodToTest(list)

    then:
    result == list

    where:
    list = Mock(List, {0 * _})
}
```

I thought the where-block is there to define variables which are used during the test.
And as you can see there are no interactions, so no verification is necessary.
The where block is the first scope I look for variables. Having a mixed mode for variable definition in the where-block and additional in the setup-block seems kind of odd to me.
  
Of course real Mocks with interactions shall be defined in the setup-block and their interactions shall be verified in the then-block. There's no doubt.

----
  
So how can you test this?

```Groovy
public List methodToTest(final boolean trueOrFalse, final List list) {
    return trueOrFalse ? list : null
}

def "methodToTest: returns the argument"() {
    when:
    final def result = methodToTest(trueOrFalse, list)

    then:
    result == expected

    where:
    trueOrFalse | list                || expected
    true        | Mock(List, {0 * _}) || list
    false       | Mock(List, {0 * _}) || null
}
```

How else can you use data tables in that example?

**Comment by sdoeringNew** [comment]
And as a fan of strict mocking I would like to have a shortcut for such no-interaction-mocks or -stubs.
Something like ``ZeroMock(List)`` which resembles to ``Mock(List, {0 * _})``.

(Of course with a better name than ``ZeroMock``.)

If that's a neat feature I'll be happy to raise another issue and prepare a pull request.

**Comment by leonard84** [comment]
Read [Lenient vs. Strict Mocking Frameworks](http://spockframework.org/spock/docs/1.1/all_in_one.html#_default_behavior_of_mock_objects) in the docs. As for what you want `Mock(List, {0 * _})` will be the shortest, and it will work even in the where block like I said above. If you generally want strict mocking just add `0 * _` as the last interaction in the then block, see [docs](http://spockframework.org/spock/docs/1.1/all_in_one.html#_strict_mocking).

>I thought the where-block is there to define variables which are used during the test.

That is not correct, generally that is what the `given`/`setup` block is for. The `where` block is used to declare variations. Since Spock is quite flexible it can of course be used that way most of the time, and @robfletcher suggested in his talks/book to move variables to the where block even if there was no variation.
