### ISSUE TITLE
Question: how can we injecting the same instance between multiple specs?

### ISSUE THREAD

**Issue by fioan89** [spockframework/spock#854]
I was looking at the implementation of [Guice Interceptor](https://github.com/spockframework/spock/blob/master/spock-guice/src/main/java/org/spockframework/guice/GuiceInterceptor.java#L62) and it seems to me that you can't have the same **injector** intercepting multiple specs. Which means an instance scoped to Singleton is limited only to a spec life-cycle.

Is that by design? What is the reason behind this choice? Is there a recommended approach to inject a singleton shared between multiple specs?

**Comment by leonard84** [comment]
Yes it is by design, real singletons and testing normally don't work well together, i.e. test pollution. What is your reason for wanting to reuse the singleton? You can use [InstanceBindings](https://github.com/google/guice/wiki/InstanceBindings) and bind to a static field that holds your singleton, of course that singleton must be constructed manually. The other way would be to don't use spocks support but use [on-demand injection](https://github.com/google/guice/wiki/Injections#on-demand-injection) and manage the injector yourself.

**Comment by fioan89** [comment]
Indeed what I did was to actually write my own extension to manage the injector. InstanceBinding also works, unless you need to inject a dependency into the singleton.

Regarding the use case - I'm writing a DSL for setting up static data for some integration/functional tests. The DSL needs a caching component, therefore I need the same instance in all the tests that use the DSL.
