### ISSUE TITLE
Ability to inject Spock mocks as Spring beans

### ISSUE THREAD

**Issue by chrylis** [spockframework/spock#86]
There was an issue on the old tracker referenced in [this SO question](http://stackoverflow.com/questions/16810646/how-to-create-spock-mocks-outside-of-a-specification-class) that doesn't appear to have been migrated. Essentially, for tests that require starting up a nontrivial application context, it would be extremely helpful to be able to create a Spock mock and easily register it as a Spring bean (especially when using Spring Boot for testing).

**Comment by leonard84** [comment]
This is implemented by #17

**Comment by jdigger** [comment]
Using a "pure Spring" approach, this is pretty easy:
```groovy
def parentAppCtx = new StaticApplicationContext()
parentAppCtx.beanFactory.registerSingleton("myBean", Mock(MyClass))
parentAppCtx.refresh()
def appCtx = new ClassPathXmlApplicationContext("spring-config.xml", parentAppCtx)
```

**Comment by leonard84** [comment]
@jdigger although this might work, it is quite limited, since you need to reload the application context for each Spec/Feature. We have a rather costly application context and it would increase our testing time tremendously to recreate it all the time.

**Comment by jgriff** [comment]
The latest [Spring Boot 1.4 Test Support](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-mocking-beans) goes a long way in this direction with its new `@MockBean` annotation.  However, it is backed by Mockito.

```groovy
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.boot.test.mock.mockito.MockBean
import spock.lang.Specification

@ContextConfiguration // should not be required, but had to include this for Spock to startup the Spring context
@SpringBootTest
class MySpec extends Specification {
    @MockBean
    MyBean mockOfMyBean
}
```

Spock support has a little catching up to do with the new cool Spring Boot 1.4 testing.

**Comment by leonard84** [comment]
@jgriff spock-1.1-rc1 already includes detached mock support.

In regards to `@MockBean` my comment above still holds AFAIK. If it is replacing beans in an already created application context it needs to recreate all beans that have dependencies on it and the context is only valid for this one class. This disables cached-context reuse between test classes which can have a serious impact on your test run times.
However, I haven't looked too deeply into the actual implementation and if they somehow got around that, then maybe we can adopt it for spock mocks as well.

**Comment by pchudzik** [comment]
I don't really know how you guys do things in spock because I use groovy only for writing tests, but I've been investigating it on spring side, and I think that spring-boot-test is not ready to be plugged with different mocking framework.

I wanted to inject spock mocks using existing spring infrastructure and since it's not yet possible here is what I was able to find out, maybe it will be helpful to someone...

Class [org.springframework.boot.test.mock.mockito.MockitoPostProcessor](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/MockitoPostProcessor.java) would be pretty good entry point to start. There is pretty promising method [org.springframework.boot.test.mock.mockito.MockitoPostProcessor#createMock](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/MockitoPostProcessor.java#L224) (with spies it is more complicated and I stopped searching after I tripped over this one), but classes [MockDefinition](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/MockDefinition.java) and [SpyDefinition](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/SpyDefinition.java) are package private (for starters) and method createMock is ```protected final``` so it is impossible to override.

Based on this in order to implement you would be forced to completely mimic MockitoPostProcessor behavior and logic in order to replace two functions responsible for mock/spy creation which is far from anything good...

imho before trying to do it in spock from scratch some changes should be made in spring-boot-test itself which will allow to plugin other mocking frameworks, and then custom implementation can be introduced in spock which will use DetachableMocks without messing with whole spring infrastructure and beans creation process.

**Comment by pchudzik** [comment]
Hi as my request in spring was rejected I've decided to do something about it and as a result I've created springmock library which allows to inject spock mocks into spock spring integration tests.

More on [my blog](https://blog.pchudzik.com/201707/springmock-v1/) and [on the project github page](https://github.com/pchudzik/springmock)

**Comment by leonard84** [comment]
@pchudzik nice work, I noticed you had some comments, e.g., Spock doesn't support additional interfaces for mocks yet, feel free to create some issues.
